### ISSUE TITLE
Fushatat nuk merren nga databaza - permission denied

### ISSUE THREAD

**Issue by ecnmst** [tiranacode/jap-jete-admin#27]
Nuk i ben load fushatave, por i ben load te dhenave te userave.

**Comment by ani12321** [comment]
Per nje spital kur logohet, gjenerohet nje session_token qe ruhet ne db.
Nese i njejti user logohet ne nje PC tjeter, ndryshon session_token, duke sjelle 'permission denied' te i pari.
@tpllaha Ndonje ide si mund ta zgjidhim kete, apo eshte ne rregull keshtu?

**Comment by tpllaha** [comment]
Nje here per nje here login e suportojme vetem nga 1 device. (edhe ne cel, edhe ne webapp) po duhet ta menaxhojme ne UI kte problem. Dmth kur merr permission denied nga backend, duhet bere redirect te faqja qe ben login.

**Comment by tpllaha** [comment]
Per momentin po e mbyll kete. Dicka qe do beja me vone do ishte suport per usera te ndryshem brenda te njejtit spital.
